### PR TITLE
move minify to end of pipeline and avoid minifying data. fixes #273 ...

### LINKED ISSUE #273: JavaScript heap out of memory
I was running following example with:
`clinic bubbleprof --on-port "autocannon  /" -- node example-server.js`

Code for example-server.js is:
```
const { promisify } = require('util')
const mongojs = require('mongojs')
const fastify = require('fastify')
const computeMagic = require('@nearform/compute-magic')

const db = mongojs('localhost:27017/npm')
const c = db.collection('modulesIndexed')
const app = fastify()

function find (modified, cb) {
  c.find().sort({modified: 1}).limit(5, cb)
}

// get 5 newest and 5 oldest, no index
app.get('/', async function (req, reply) {
  try {
    const pFind = promisify(find)
    const [newest, oldest] = await Promise.all([
      pFind(1),
      pFind(-1)
    ])
    reply.send({
      newest,
      oldest
    })
  } catch(err) {
    return reply.code(500).send(err)
  }
})

app.listen(3000)
```
and here is the output i got
```
100 connections

Stat    2.5%   50%    97.5%  99%    Avg      Stdev    Max
Latency 364 ms 380 ms 530 ms 534 ms 401.3 ms 48.01 ms 564.55 ms

Stat      1%     2.5%   50%    97.5%  Avg    Stdev   Min
Req/Sec   200    200    203    300    240.5  47.59   200
Bytes/Sec 220 kB 220 kB 224 kB 331 kB 265 kB 52.4 kB 220 kB

Req/Bytes counts sampled once per second.

2k requests in 10.05s, 2.65 MB read
Analysing data

<--- Last few GCs --->

[80251:0x103800c00]    46419 ms: Scavenge 1394.0 (1421.3) -> 1393.3 (1422.3) MB, 4.3 / 0.0 ms  (average mu = 0.153,
 current mu = 0.079) allocation failure
[80251:0x103800c00]    46425 ms: Scavenge 1394.2 (1422.3) -> 1393.6 (1422.8) MB, 3.9 / 0.0 ms  (average mu = 0.153,
 current mu = 0.079) allocation failure
[80251:0x103800c00]    46431 ms: Scavenge 1394.4 (1422.8) -> 1393.8 (1423.3) MB, 3.8 / 0.0 ms  (average mu = 0.153,
 current mu = 0.079) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1d6affddbe3d]
Security context: 0x24ba1c39e6e1 <JSObject>
    1: d(aka d) [0x24ba39499f69] [/Users/klemenk/.nvm/versions/node/v10.13.0/lib/node_modules/clinic/node_modules/t
erser/dist/bundle.js:~44] [pc=0x1d6b0031bb16](this=0x24ba03a826f1 <undefined>,t=0x24ba62971499 <String[4]: punc>,i=
0x24bac928b169 <String[1]: :>,o=0x24ba03a826f1 <undefined>)
    2: arguments adaptor frame: 2->3
    3: B [0x24ba394981d1] [/Users...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003ae75 node::Abort() [/Users/klemenk/.nvm/versions/node/v10.13.0/bin/node]
 2: 0x10003b07f node::OnFatalError(char const*, char const*) [/Users/klemenk/.nvm/versions/node/v10.13.0/bin/node]
 3: 0x1001a7ae5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/klemen
k/.nvm/versions/node/v10.13.0/bin/node]
 4: 0x100572ef2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/klemenk/.nvm/versions/node/v10.13.
0/bin/node]
 5: 0x1005759c5 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/klemenk/.nvm/version
s/node/v10.13.0/bin/node]
 6: 0x10057186f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [
/Users/klemenk/.nvm/versions/node/v10.13.0/bin/node]
 7: 0x10056fa44 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionRe
ason, v8::GCCallbackFlags) [/Users/klemenk/.nvm/versions/node/v10.13.0/bin/node]
 8: 0x10057c2dc v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::All
ocationAlignment) [/Users/klemenk/.nvm/versions/node/v10.13.0/bin/node]
 9: 0x10057c35f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::Al
locationAlignment) [/Users/klemenk/.nvm/versions/node/v10.13.0/bin/node]
10: 0x10054bca4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/klemenk/.n
vm/versions/node/v10.13.0/bin/node]
11: 0x1007d3b54 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Use
rs/klemenk/.nvm/versions/node/v10.13.0/bin/node]
12: 0x1d6affddbe3d
13: 0x1d6b0031bb16
14: 0x1d6affd8a5c3
15: 0x1d6b001d7eda
[1]    80251 abort      clinic bubbleprof --on-port "autocannon -d 10 -c 100 /" -- node example-server.js
```
Version of clinicjs is v2.0.0

### PR DESCRIPTION
**Pull request by mafintosh**
… and https://github.com/nearform/node-clinic/issues/72

Currently the minification pipeline will run out of memory on even pretty small analysises as it's trying to minify all the inlined data, which doesn't make a lot of sense.

This PR fixes this by applying two changes.

It moves the minification to after the the viz pipeline has finished (it needs to buffer anyway, see the source of minify-stream). This should in theory free up all the memory used by the analysis to be avail for minification but there seems to be a leak somewhere (TODO: investigate why node keeps retaining all the sourcenodes/frames *after* all the refs to the streams are gone).

It also applies so hacks to strip out the data from the source before passing it to the minifier. This speeds up the minification massively and also reduces the memory usage to be negligible.

### CODE REVIEW

File: lib/minify-inline.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
+const terser = require('terser')
```
Comment (mcollina) [inline lib/minify-inline.js]: can you stick a `'use strict'` at the top?

File: lib/minify-inline.js [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+    if (err) return cb(err)
+
+    const start = data.indexOf('<script>')
+    const end = data.lastIndexOf('</script>')
+
+    if (start === -1 || end === -1) return cb(new Error('Must contain <script> and </script> tags'))
+
+    const src = data.slice(start + 8, end) // + 8 === <script>.length
+    const magicPrefix = 'module.exports={"data":['
+    const magic = '"__MAGIC_MINIFY_UNIQUE_STRING_TO_BE_REPLACED__"'
```
Comment (mcollina) [inline lib/minify-inline.js]: nice one! _should_ it be replaced?

File: lib/minify-inline.js [hunk 3]
```diff
@@ -0,0 +1,35 @@
+const terser = require('terser')
+const fs = require('fs')
+
+module.exports = minifyInline
+
+function minifyInline (filename, opts, cb) {
```
Comment (mcollina) [inline lib/minify-inline.js]: Can you add a comment here describing what this function does?

File: lib/minify-inline.js (hunk 2 above)
Comment (mafintosh) [reply lib/minify-inline.js]: Yes, I'll make that more clear

File: lib/minify-inline.js (hunk 1 above)
Comment (mafintosh) [reply lib/minify-inline.js]: Fixed

File: lib/minify-inline.js (hunk 3 above)
Comment (mafintosh) [reply lib/minify-inline.js]: Fixed
